version: '3'

volumes:
  postgres_test_project_data: {}

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=someSuperPass2020
    container_name: postgres_test_project
    volumes:
      - postgres_test_project_data:/var/lib/postgresql/data

  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py loaddata db.json && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: django_test_project